/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Arboles.AVL;
import Arboles.ArbolBinarioBusqueda;
import Arboles.IArbolBusqueda;
import excepciones.ExcepcionClaveNoExiste;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HAROLD
 */

public class MBinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    
    public MBinario() {
        
        initComponents();
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Mostrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Reconstruir1 = new javax.swing.JLabel();
        preOrden = new javax.swing.JButton();
        postOrden = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        Reconstruir4 = new javax.swing.JLabel();
        Reconstruir5 = new javax.swing.JLabel();
        nodoPadre = new javax.swing.JButton();
        nodoHijo = new javax.swing.JButton();
        existe = new javax.swing.JButton();
        Reconstruir6 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostrarAVL = new javax.swing.JTextArea();
        claveA = new javax.swing.JTextField();
        Reconstruir2 = new javax.swing.JLabel();
        valorA = new javax.swing.JTextField();
        Reconstruir3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalles = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Mostrar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Reconstruir7 = new javax.swing.JLabel();
        preOrdenAVL = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Reconstruir8 = new javax.swing.JLabel();
        Reconstruir9 = new javax.swing.JLabel();
        similar = new javax.swing.JButton();
        equivalente = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Reconstruir10 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        vaciar = new javax.swing.JButton();
        Mostrar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        mostrarArbol1 = new javax.swing.JTextArea();
        vaciar2 = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Lista In Orden = (\"alegria\", \"amistad\", \"amor\", \"armonia\", \"dignidad\", \"esperanzas\", \"felicidad\", \"fuerza\", \"gratitud\",\"humildad\", \"igualdad\", \"libertad\", \"luz\", \"paz\", \"perdon\", \"pureza\", \"respeto\", \"salud\", \"union\")");

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        Reconstruir1.setText("Reconstruir ");

        preOrden.setText("Pre-Orden");
        preOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrdenActionPerformed(evt);
            }
        });

        postOrden.setText("Post-Orden");
        postOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postOrdenActionPerformed(evt);
            }
        });

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        insertar.setText("INSERTAR");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        Reconstruir4.setText("Modificar ");

        Reconstruir5.setText("Consultas");

        nodoPadre.setText("Es Nodo Padre");
        nodoPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodoPadreActionPerformed(evt);
            }
        });

        nodoHijo.setText("Es Nodo Hoja");
        nodoHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodoHijoActionPerformed(evt);
            }
        });

        existe.setText("EXISTE");
        existe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existeActionPerformed(evt);
            }
        });

        Reconstruir6.setText("Retornar");

        result.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        result.setText("RETURN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reconstruir4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reconstruir1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reconstruir5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reconstruir6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(preOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(postOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nodoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(existe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nodoHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Reconstruir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reconstruir4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reconstruir5)
                .addGap(5, 5, 5)
                .addComponent(existe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nodoPadre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nodoHijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reconstruir6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("ARBOL A");

        jLabel4.setText("Lista Pre Orden =(\"humildad\", \"dignidad\", \"amistad\", \"alegria\", \"amor\", \"armonia\", \"felicidad\", \"esperanzas\", \"fuerza\", \"gratitud\", \"perdon\", \"luz\", \"igualdad\", \"libertad\", \"paz\", \"respeto\", \"pureza\", \"salud\", \"union\")");

        mostrarAVL.setColumns(20);
        mostrarAVL.setRows(5);
        jScrollPane2.setViewportView(mostrarAVL);

        Reconstruir2.setText("CLAVE = ");

        valorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorAActionPerformed(evt);
            }
        });

        Reconstruir3.setText("VALOR =");

        detalles.setColumns(20);
        detalles.setRows(5);
        jScrollPane1.setViewportView(detalles);

        jLabel5.setText("List Post Orden = (\"alegria\",  \"armonia\",\"amor\", \"amistad\", \"esperanzas\", \"gratitud\", \"fuerza\", \"felicidad\", \"dignidad\", \"libertad\",\"igualdad\", \"paz\", \"luz\", \"pureza\", \"union\", \"salud\", \"respeto\", \"perdon\", \"humildad\")");

        jLabel6.setBackground(new java.awt.Color(255, 255, 102));
        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("ARBOL B");

        Mostrar1.setText("Mostrar");
        Mostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar1ActionPerformed(evt);
            }
        });

        Reconstruir7.setText("Reconstruir ");

        preOrdenAVL.setText("Pre-Orden");
        preOrdenAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrdenAVLActionPerformed(evt);
            }
        });

        jButton13.setText("Post-Orden");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("ELIMINAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("INSERTAR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("BUSCAR");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        Reconstruir8.setText("Modificar ");

        Reconstruir9.setText("Consultas");

        similar.setText("SIMILARES");
        similar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                similarActionPerformed(evt);
            }
        });

        equivalente.setText("EQUIVALENTES");
        equivalente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equivalenteActionPerformed(evt);
            }
        });

        jButton19.setText("EXISTE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        Reconstruir10.setText("Retornar");

        result1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        result1.setText("RETURN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reconstruir8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reconstruir7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reconstruir9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reconstruir10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(preOrdenAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(similar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Reconstruir7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preOrdenAVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reconstruir8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reconstruir9)
                .addGap(5, 5, 5)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(similar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equivalente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reconstruir10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vaciar.setText("Vaciar");
        vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarActionPerformed(evt);
            }
        });

        Mostrar2.setText("cambiar");
        Mostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar2ActionPerformed(evt);
            }
        });

        mostrarArbol1.setColumns(20);
        mostrarArbol1.setRows(5);
        jScrollPane3.setViewportView(mostrarArbol1);

        vaciar2.setText("Vaciar");
        vaciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(Mostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vaciar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Reconstruir3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Reconstruir2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(claveA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Mostrar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Mostrar1)
                        .addGap(18, 18, 18)
                        .addComponent(vaciar2)))
                .addGap(0, 759, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Mostrar2)
                        .addComponent(Mostrar1)
                        .addComponent(vaciar2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(Mostrar)
                                .addComponent(vaciar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(claveA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 537, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean arbolDeCero = true;
    boolean arbolDeCero2 = true;
    boolean arbolAVLDeCero = true;
    IArbolBusqueda<String,Integer> arbol = new ArbolBinarioBusqueda<>();
    public ArbolBinarioBusqueda<String,Integer> arbolBinario = (ArbolBinarioBusqueda<String,Integer>) arbol;
    
    ArbolBinarioBusqueda<String,Integer> arbolBinario2 = (ArbolBinarioBusqueda<String,Integer>) arbol;
    AVL<String,Integer> arbolAVL = new AVL<>();
    
    boolean bAVL = false;
    //listas en INORDEN
    List<String> listaKInOrden = new ArrayList<>(
            Arrays.asList("alegria", "amistad", "amor", "armonia", "dignidad", "esperanzas", "felicidad", "fuerza", "gratitud",
            "humildad", "igualdad", "libertad", "luz", "paz", "perdon", "pureza", "respeto", "salud", "union"));
    List<Integer> listaVInOrden = new ArrayList<>(
            Arrays.asList(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190));

    //LISTAS PREORDEN
    List<String> listaKPreOrden = new ArrayList<>(
            Arrays.asList("humildad", "dignidad", "amistad", "alegria", "amor", "armonia", "felicidad", "esperanzas", "fuerza", "gratitud",
            "perdon", "luz", "igualdad", "libertad", "paz", "respeto", "pureza", "salud", "union"));
    List<Integer> listaVPreOrden = new ArrayList<>(
            Arrays.asList(100, 50, 20, 10, 30, 40, 70, 60, 80, 90, 150, 130, 110, 120, 140, 170, 160, 180, 190));

    //LISTAS POSTORDEN
    List<String> listaKPostOrden = new ArrayList<>(
            Arrays.asList("alegria", "armonia", "amor", "amistad", "esperanzas", "gratitud", "fuerza", "felicidad", "dignidad", "libertad",
            "igualdad", "paz", "luz", "pureza", "union", "salud", "respeto", "perdon", "humildad"));
    List<Integer> listaVPostOrden = new ArrayList<>(
            Arrays.asList(10, 30, 40, 20, 60, 90, 80, 70, 50, 120, 110, 140, 130, 160, 190, 180, 170, 150, 100));
    
    private String mostrar(ArbolBinarioBusqueda<String,Integer> arbol){
        //ArbolBinarioBusqueda<String,Integer> arbolBinario = (ArbolBinarioBusqueda<String,Integer>)arbol;
        String cad = ""; 
        cad = "RECORRIDOS\n";
        cad = cad + "Por Niveles" + arbol.recorridoPorNiveles() + "\n"; 
        cad = cad + "Por InOrden " + arbol.recorridoEnInOrdenRe() + "\n";
        cad = cad + "Por PreOrden" +arbol.recorridoEnPreOrden() + "\n";
        cad = cad + "Por PosOrden" + arbol.recorridoEnPostOrden() + "\n";
        cad = cad + "Altura Arbol: " + arbol.altura() + "\n";
        cad = cad + "Nivel Arbol : "+ arbol.nivel() + "\n";
        cad = cad + "Max Arbol : "+ arbol.maximo() + "\n";
        cad = cad + "Min Arbol : "+ arbol.minimo() + "\n";
        return cad;
    }
    
    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        this.mostrarArbol1.setText(arbolBinario.toString());
        this.detalles.setText(this.mostrar(arbolBinario));
    }//GEN-LAST:event_MostrarActionPerformed

    private void postOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postOrdenActionPerformed
        arbolBinario = new ArbolBinarioBusqueda<>(listaKInOrden,listaVInOrden,listaKPostOrden,listaVPostOrden,false);
        arbolDeCero = false;
    }//GEN-LAST:event_postOrdenActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            Integer eliminar = arbolBinario.eliminar(claveA.getText());
            result.setText(String.valueOf(eliminar));
        } catch (ExcepcionClaveNoExiste ex) {
            Logger.getLogger(MBinario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        if (arbolDeCero){
            arbolBinario = new ArbolBinarioBusqueda<>();
            arbolDeCero = false;
        }
        Integer valor = Integer.valueOf(valorA.getText() );
        arbolBinario.insertar(claveA.getText(), valor);
    }//GEN-LAST:event_insertarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        result.setText( String.valueOf(arbolBinario.buscar(claveA.getText()) ) );
    }//GEN-LAST:event_buscarActionPerformed

    private void nodoHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodoHijoActionPerformed
        if (!arbolBinario.esNodoPadre(claveA.getText()) && (arbolBinario.contiene(claveA.getText())) ){
            result.setText("TRUE");
        }else{
            result.setText("FALSE");
        }
    }//GEN-LAST:event_nodoHijoActionPerformed

    private void preOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrdenActionPerformed
        arbolBinario = new ArbolBinarioBusqueda<>(listaKInOrden,listaVInOrden,listaKPreOrden,listaVPreOrden,true);
        arbolDeCero = false;
    }//GEN-LAST:event_preOrdenActionPerformed

    private void valorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorAActionPerformed

    private void existeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existeActionPerformed
        if (arbolBinario.contiene(claveA.getText())){
            result.setText("TRUE");
        }else{
            result.setText("FALSE");
        }
    }//GEN-LAST:event_existeActionPerformed

    private void Mostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar1ActionPerformed
        if (!bAVL){
            this.mostrarAVL.setText(arbolBinario2.toString());
            this.detalles.setText(this.mostrar(arbolBinario2));
        }else {
            this.mostrarAVL.setText(arbolAVL.toString());
            this.detalles.setText(this.mostrar(arbolAVL));
        }
    }//GEN-LAST:event_Mostrar1ActionPerformed

    private void preOrdenAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrdenAVLActionPerformed
        if (!bAVL){
            arbolBinario2 = new ArbolBinarioBusqueda<>(listaKInOrden,listaVInOrden,listaKPreOrden,listaVPreOrden,true);
            arbolDeCero2 = false;
        }else {
            arbolAVL.insertar("humildad",1); arbolAVL.insertar("dignidad",1); arbolAVL.insertar("perdon",1);
            arbolAVL.insertar("amistad",1); arbolAVL.insertar("felicidad",1); arbolAVL.insertar("luz",1);
            arbolAVL.insertar("respeto",1); arbolAVL.insertar("alegria",1); arbolAVL.insertar("amor",1); arbolAVL.insertar("esperanzas",1);
            arbolAVL.insertar("fuerzas",1); arbolAVL.insertar("igualdad",1); arbolAVL.insertar("paz",1);
            arbolAVL.insertar("pureza",1); arbolAVL.insertar("salud",1); arbolAVL.insertar("armonia",1);
            arbolAVL.insertar("gratitud",1); arbolAVL.insertar("libertad",1); arbolAVL.insertar("union",1); 
            arbolAVLDeCero = false;
        }
        
        
    }//GEN-LAST:event_preOrdenAVLActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        arbolBinario2 = new ArbolBinarioBusqueda<>(listaKInOrden,listaVInOrden,listaKPostOrden,listaVPostOrden,false);
        arbolDeCero2 = false;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Integer eliminar;
        if (!bAVL){
            try {
                eliminar = arbolBinario2.eliminar(claveA.getText());
                result1.setText(String.valueOf(eliminar));
            } catch (ExcepcionClaveNoExiste ex) {
                Logger.getLogger(MBinario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            eliminar = arbolAVL.eliminar(claveA.getText());
            result1.setText(String.valueOf(eliminar));
        }        
        
       
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (!bAVL){
            if (arbolDeCero2){
                arbolBinario2 = new ArbolBinarioBusqueda<>();
                arbolDeCero2 = false;
            }
            Integer valor = Integer.valueOf(valorA.getText() );
            arbolBinario2.insertar(claveA.getText(), valor);
        }else {
            if (arbolAVLDeCero) {
                arbolAVL = new AVL<>();
                arbolAVLDeCero = false;
            }
            Integer valor = Integer.valueOf(valorA.getText());
            arbolAVL.insertar(claveA.getText(), valor);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (!bAVL){
            result1.setText( String.valueOf(arbolBinario2.buscar(claveA.getText()) ) );
        }else {
            result1.setText( String.valueOf(arbolAVL.buscar(claveA.getText()) ) );
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void equivalenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equivalenteActionPerformed
        if (!bAVL){
            if (arbolBinario.esIdentico(arbolBinario2)){
                result1.setText("TRUE");
            }else {
                result1.setText("FALSE");
            }
        }else {
            if (arbolAVL.esIdentico(arbolBinario)){
             result1.setText("TRUE");
            }else {
                result1.setText("FALSE");
            }
        }        
        
    }//GEN-LAST:event_equivalenteActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (!bAVL){
            if (arbolBinario2.contiene(claveA.getText())){
                result1.setText("TRUE");
            }else{
                result1.setText("FALSE");
            }
        }else {
            if (arbolAVL.contiene(claveA.getText())){
                result1.setText("TRUE");
            }else{
                result1.setText("FALSE");
            }
        }
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void nodoPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodoPadreActionPerformed
        if (arbolBinario.esNodoPadre(claveA.getText())){
            result.setText("TRUE");
        }else{
            result.setText("FALSE");
        }
    }//GEN-LAST:event_nodoPadreActionPerformed

    private void vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarActionPerformed
        arbolBinario.vaciar();
    }//GEN-LAST:event_vaciarActionPerformed

    private void similarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_similarActionPerformed
        if (!bAVL){
            if (arbolBinario.esSimilar(arbolBinario2)){
                result1.setText("TRUE");
            }else {
                result1.setText("FALSE");
            }
        }else {
            if (arbolAVL.esSimilar(arbolBinario)){
                result1.setText("TRUE");
            }else {
                result1.setText("FALSE");
            }
        }
    }//GEN-LAST:event_similarActionPerformed

    private void Mostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar2ActionPerformed
        if (!bAVL){
            jLabel6.setText("AVL");
            bAVL = true; 
            preOrdenAVL.setText("inOrden");
            jButton13.show(false);
        }else {
            jLabel6.setText("ARBOL B");
            bAVL = false;
            preOrdenAVL.setText("Pre-Orden");
            jButton13.show(true);
        }
        
    }//GEN-LAST:event_Mostrar2ActionPerformed

    private void vaciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciar2ActionPerformed
        if (!bAVL){
            arbolBinario2.vaciar();
        }else {
            arbolAVL.vaciar();
        }
    }//GEN-LAST:event_vaciar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Mostrar1;
    private javax.swing.JButton Mostrar2;
    private javax.swing.JLabel Reconstruir1;
    private javax.swing.JLabel Reconstruir10;
    private javax.swing.JLabel Reconstruir2;
    private javax.swing.JLabel Reconstruir3;
    private javax.swing.JLabel Reconstruir4;
    private javax.swing.JLabel Reconstruir5;
    private javax.swing.JLabel Reconstruir6;
    private javax.swing.JLabel Reconstruir7;
    private javax.swing.JLabel Reconstruir8;
    private javax.swing.JLabel Reconstruir9;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField claveA;
    private javax.swing.JTextArea detalles;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton equivalente;
    private javax.swing.JButton existe;
    private javax.swing.JButton insertar;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea mostrarAVL;
    private javax.swing.JTextArea mostrarArbol1;
    private javax.swing.JButton nodoHijo;
    private javax.swing.JButton nodoPadre;
    private javax.swing.JButton postOrden;
    private javax.swing.JButton preOrden;
    private javax.swing.JButton preOrdenAVL;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result1;
    private javax.swing.JButton similar;
    private javax.swing.JButton vaciar;
    private javax.swing.JButton vaciar2;
    private javax.swing.JTextField valorA;
    // End of variables declaration//GEN-END:variables
}
