/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Arboles.AVL;
import Arboles.ArbolB;
import Arboles.ArbolBinarioBusqueda;
import Arboles.ArbolMViasBusqueda;
import Arboles.IArbolBusqueda;
import excepciones.ExcepcionClaveNoExiste;
import excepciones.ExcepcionOrdenInvalido;
import java.awt.Image;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author HAROLD
 */

public class MViasB extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    
    public MViasB() {
        
        initComponents();
       //this.printImage(this.jLabel1, "Untitled.png");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        claveA = new javax.swing.JTextField();
        Reconstruir2 = new javax.swing.JLabel();
        valorA = new javax.swing.JTextField();
        Reconstruir3 = new javax.swing.JLabel();
        Mostrar = new javax.swing.JButton();
        vaciar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Reconstruir1 = new javax.swing.JLabel();
        insercion = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        Reconstruir4 = new javax.swing.JLabel();
        Reconstruir5 = new javax.swing.JLabel();
        existe = new javax.swing.JButton();
        Reconstruir6 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        similar = new javax.swing.JButton();
        buscar6 = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        vaciar6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Mostrar8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Reconstruir37 = new javax.swing.JLabel();
        ejemplo1 = new javax.swing.JButton();
        ejmplo2 = new javax.swing.JButton();
        insertar5 = new javax.swing.JButton();
        buscar5 = new javax.swing.JButton();
        Reconstruir38 = new javax.swing.JLabel();
        Reconstruir39 = new javax.swing.JLabel();
        existe5 = new javax.swing.JButton();
        Reconstruir40 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        detalles2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalles1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        mostrarArbol1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        mostrarArbol2 = new javax.swing.JTextArea();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("MVIAS");

        Reconstruir2.setText("CLAVE = ");

        valorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorAActionPerformed(evt);
            }
        });

        Reconstruir3.setText("VALOR =");

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        vaciar.setText("Vaciar");
        vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarActionPerformed(evt);
            }
        });

        Reconstruir1.setText("Reconstruir ");

        insercion.setText("inserccion");
        insercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insercionActionPerformed(evt);
            }
        });

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        insertar.setText("INSERTAR");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        Reconstruir4.setText("Modificar ");

        Reconstruir5.setText("Consultas");

        existe.setText("EXISTE");
        existe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existeActionPerformed(evt);
            }
        });

        Reconstruir6.setText("Retornar");

        result.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        result.setText("RETURN");

        similar.setText("BALANCEADO");
        similar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                similarActionPerformed(evt);
            }
        });

        buscar6.setText("# DE HOJAS");
        buscar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar6buscar4ActionPerformed(evt);
            }
        });

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Reconstruir4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Reconstruir1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Reconstruir5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Reconstruir6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buscar6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(similar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(existe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insercion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reconstruir1)
                .addGap(5, 5, 5)
                .addComponent(insercion)
                .addGap(10, 10, 10)
                .addComponent(Reconstruir4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reconstruir5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(existe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(similar)
                .addGap(18, 18, 18)
                .addComponent(Reconstruir6)
                .addGap(4, 4, 4)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vaciar6.setText("Vaciar");
        vaciar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciar6ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 102));
        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("ARBOL B");

        Mostrar8.setText("Mostrar");
        Mostrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar8ActionPerformed(evt);
            }
        });

        Reconstruir37.setText("Reconstruir ");

        ejemplo1.setText("ejemplo 1");
        ejemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porNivele2ActionPerformed(evt);
            }
        });

        ejmplo2.setText("ejemplo 2");
        ejmplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postOrden4ActionPerformed(evt);
            }
        });

        insertar5.setText("INSERTAR");
        insertar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertar4ActionPerformed(evt);
            }
        });

        buscar5.setText("BUSCAR");
        buscar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar4ActionPerformed(evt);
            }
        });

        Reconstruir38.setText("Modificar ");

        Reconstruir39.setText("Consultas");

        existe5.setText("EXISTE");
        existe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existe4ActionPerformed(evt);
            }
        });

        Reconstruir40.setText("Retornar");

        result1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        result1.setText("RETURN");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(result1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Reconstruir38, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir37, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir39, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir40, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscar5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(existe5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertar5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ejmplo2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ejemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(Reconstruir37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejemplo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejmplo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reconstruir38)
                .addGap(10, 10, 10)
                .addComponent(insertar5)
                .addGap(14, 14, 14)
                .addComponent(Reconstruir39)
                .addGap(5, 5, 5)
                .addComponent(existe5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reconstruir40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        detalles2.setColumns(20);
        detalles2.setRows(5);
        jScrollPane4.setViewportView(detalles2);

        detalles1.setColumns(20);
        detalles1.setRows(5);
        jScrollPane2.setViewportView(detalles1);

        mostrarArbol1.setColumns(20);
        mostrarArbol1.setRows(5);
        jScrollPane3.setViewportView(mostrarArbol1);

        mostrarArbol2.setColumns(20);
        mostrarArbol2.setRows(5);
        jScrollPane5.setViewportView(mostrarArbol2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Mostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vaciar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Reconstruir3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(claveA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(Mostrar8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaciar6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mostrar8)
                            .addComponent(vaciar6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(claveA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reconstruir3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Mostrar)
                                    .addComponent(vaciar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(391, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    boolean arbolDeCero = true;    
    
    ArbolMViasBusqueda<Integer,String> arbolMV = new ArbolMViasBusqueda<>();
    ArbolB<Integer,String> arbolB = new ArbolB<>();
    
    
    private String mostrar(ArbolMViasBusqueda<Integer,String> arbol){
        //ArbolBinarioBusqueda<String,Integer> arbolBinario = (ArbolBinarioBusqueda<String,Integer>)arbol;
        String cad = ""; 
        cad = "RECORRIDOS\n";
        cad = cad + "Por Niveles" + arbol.recorridoPorNiveles() + "\n"; 
        cad = cad + "Por PreOrden" +arbol.recorridoEnPreOrden() + "\n";
        cad = cad + "Por InOrden " + arbol.recorridoEnInOrden() + "\n";
        cad = cad + "Por PosOrden" + arbol.recorridoEnPostOrden() + "\n";
        cad = cad + "Altura Arbol: " + arbol.altura() + "\n";
        cad = cad + "Nivel Arbol : "+ arbol.nivel() + "\n";
        cad = cad + "Tamaño Arbol : "+ arbol.sixe() + "\n";
        cad = cad + "Max Arbol : "+ arbol.menorClave() + "\n";
        cad = cad + "Min Arbol : "+ arbol.mayorClave() + "\n";
        return cad;
    }
    
    private String mostrar(ArbolB<Integer,String> arbol){
        //ArbolBinarioBusqueda<String,Integer> arbolBinario = (ArbolBinarioBusqueda<String,Integer>)arbol;
        String cad = ""; 
        cad = "RECORRIDOS\n";
        cad = cad + "Por Niveles" + arbol.recorridoPorNiveles() + "\n"; 
        cad = cad + "Por PreOrden" +arbol.recorridoEnPreOrden() + "\n";
        cad = cad + "Por InOrden " + arbol.recorridoEnInOrden() + "\n";
        cad = cad + "Por PosOrden" + arbol.recorridoEnPostOrden() + "\n";
        cad = cad + "Altura Arbol: " + arbol.altura() + "\n";
        cad = cad + "Nivel Arbol : "+ arbol.nivel() + "\n";
        cad = cad + "Nivel Arbol : "+ arbol.sixe() + "\n";
//        cad = cad + "Max Arbol : "+ arbol.maximo() + "\n";
//        cad = cad + "Min Arbol : "+ arbol.minimo() + "\n";
        return cad;
    }
    
//    private void printImage(JLabel lbl, String ruta){
//         this.imagen = new ImageIcon("D:\\6TO SEMESTRE\\ESTRUC. DE DATOS II\\PROGRAMAS ED2\\ED2_SEMESTRE_1_21\\src\\main\\java\\proyecto\\Untitled.png"); 
//        this.icono = new ImageIcon(
//                this.imagen.getImage().getScaledInstance(
//                        lbl.getWidth(),
//                        lbl.getHeight(),
//                        Image.SCALE_DEFAULT
//                )
//        );
//        lbl.setIcon(this.icono);
//        this.repaint();
//    }
    private void valorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorAActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        this.mostrarArbol2.setText(arbolMV.toString());
        this.detalles1.setText(this.mostrar(arbolMV));
    }//GEN-LAST:event_MostrarActionPerformed

    private void vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarActionPerformed
        arbolMV.vaciar();
    }//GEN-LAST:event_vaciarActionPerformed

    private void insercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insercionActionPerformed
        try {
            arbolMV = new ArbolMViasBusqueda<>(4);
            arbolMV.insertar(120, "ciento veinte");
            arbolMV.insertar(200, "doscientos");
            arbolMV.insertar(80, "ochenta");
            arbolMV.insertar(150, "ciento cincuenta");
            arbolMV.insertar(130, "ciento treinta");
            arbolMV.insertar(50, "cincuenta");
            arbolMV.insertar(140, "ciento cuarenta");
            arbolMV.insertar(134, "ciento treinta");
            arbolMV.insertar(70, "setenta");
            arbolMV.insertar(75, "setenta y cinco");
            arbolMV.insertar(72, "setenta y dos");
            
            arbolMV.insertar(98, "noventa y ocho");
            arbolMV.insertar(110, "ciento diez");
            arbolMV.insertar(400, "cuatrocientos");   
            
            arbolMV.insertar(160, "cien sesenta ");
            arbolMV.insertar(170, "ciento setenta");
            arbolMV.insertar(190, "ciento noventa");
            arbolMV.insertar(158, "ciento cincuenta y ocho");
            
            arbolMV.insertar(500, "quinientos");
            
            arbolMV.insertar(560, "quinientos sesenta");
            arbolDeCero = false;
        } catch (ExcepcionOrdenInvalido ex) {
            Logger.getLogger(MViasB.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_insercionActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
 
        Integer n = Integer.valueOf(claveA.getText());
        boolean e ;
        try {
            result.setText(arbolMV.eliminar(n));
        } catch (ExcepcionClaveNoExiste ex) {
            Logger.getLogger(MViasB.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_eliminarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        if (arbolDeCero){
            arbolMV = new ArbolMViasBusqueda<>();
            arbolDeCero = false;
        }
        String valor = String.valueOf(valorA.getText()) ;
        Integer clave = Integer.valueOf(claveA.getText());
        arbolMV.insertar(clave, valor);
    }//GEN-LAST:event_insertarActionPerformed

    private void existeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existeActionPerformed
        if (arbolMV.contiene(Integer.valueOf(claveA.getText()))) {
            result.setText("TRUE");
        } else {
            result.setText("FALSE");
        }
    }//GEN-LAST:event_existeActionPerformed

    private void similarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_similarActionPerformed
        if (arbolMV.pregunta7()) {
            result.setText("TRUE");
        } else {
            result.setText("FALSE");
        }
    }//GEN-LAST:event_similarActionPerformed

    private void existe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existe4ActionPerformed
        if (arbolB.contiene(Integer.valueOf(claveA.getText()))) {
            result1.setText("TRUE");
        } else {
            result1.setText("FALSE");
        }
    }//GEN-LAST:event_existe4ActionPerformed

    private void buscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar4ActionPerformed
        int clave = Integer.valueOf(claveA.getText());
        result1.setText(arbolB.buscar( clave ) );
    }//GEN-LAST:event_buscar4ActionPerformed

    private void insertar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertar4ActionPerformed
        if (arbolDeCero){
            arbolMV = new ArbolMViasBusqueda<>();
            arbolDeCero = false;
        }

        Integer clave = Integer.valueOf(claveA.getText());
        arbolB.insertar(clave, valorA.getText());
    }//GEN-LAST:event_insertar4ActionPerformed

    private void postOrden4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postOrden4ActionPerformed
        try {
            arbolB = new ArbolB<>(4);
                                                                                                                                                                                 
//            arbolB.insertar(960, "novecientos sesenta");
//            arbolB.insertar(950, "novecientos cincuenta");
//            arbolB.insertar(920, "novecientos veinte");
//            arbolB.insertar(890, "ochocientos noventa");
//            arbolB.insertar(870, "ochocientos setenta");
//            arbolB.insertar(868, "ochocientos seseinta y ocho");
//            arbolB.insertar(862, "ochocientos seseinta y dos");
//            arbolB.insertar(855, "ochocientos cincuenta y cinco");
//            arbolB.insertar(850, "ochocientos cincuenta");
//            arbolB.insertar(800, "ochocientos");
//            arbolB.insertar(500, "quinientos");
//            arbolB.insertar(400, "cuatrocientos");
//            arbolB.insertar(300, "trescientos");
//            arbolB.insertar(100, "cien");
//            arbolB.insertar(99, "noventa y nueve");
//            arbolB.insertar(91, "noventa y uno");
//            arbolB.insertar(90, "noventa");
//            arbolB.insertar(75, "setenta y cinco");
//            arbolB.insertar(70, "setenta");
//            arbolB.insertar(50, "cincuenta");
            arbolB.insertar(50, "cincuenta");
            arbolB.insertar(70, "setenta");
            arbolB.insertar(75, "setenta y cinco");
            arbolB.insertar(90, "noventa");
            arbolB.insertar(91, "noventa y uno");
            arbolB.insertar(99, "noventa y nueve");
            
            arbolB.insertar(100, "cien");
            arbolB.insertar(300, "trescientos");
            arbolB.insertar(400, "cuatrocientos");
            arbolB.insertar(500, "quinientos");
            arbolB.insertar(800, "ochocientos");
            arbolB.insertar(850, "ochocientos cincuenta");
            arbolB.insertar(855, "ochocientos cincuenta y cinco");
            arbolB.insertar(862, "ochocientos seseinta y dos");
            arbolB.insertar(868, "ochocientos seseinta y ocho");
            arbolB.insertar(870, "ochocientos setenta");
            arbolB.insertar(890, "ochocientos noventa");
            arbolB.insertar(920, "novecientos veinte");
            arbolB.insertar(950, "novecientos cincuenta");
            arbolB.insertar(960, "novecientos sesenta");
        } catch (ExcepcionOrdenInvalido ex) {
            Logger.getLogger(MViasB.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_postOrden4ActionPerformed

    private void porNivele2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porNivele2ActionPerformed
           try {
            arbolB = new ArbolB<>(4);
            arbolB.insertar(300, "trescientos");
            arbolB.insertar(500, "quinientos");
            arbolB.insertar(100, "cien");
            arbolB.insertar(50, "cincuenta");
            arbolB.insertar(400, "cuatrocientos");
            arbolB.insertar(800, "ochocientos");
            arbolB.insertar(90, "noventa");
            arbolB.insertar(91, "noventa y uno");
            arbolB.insertar(70, "setenta");
            arbolB.insertar(75, "setenta y cinco");
            arbolB.insertar(99, "noventa y nueve");

        } catch (ExcepcionOrdenInvalido ex) {
            Logger.getLogger(MViasB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_porNivele2ActionPerformed

    private void Mostrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar8ActionPerformed
        this.mostrarArbol1.setText(arbolB.toString());
        this.detalles2.setText(this.mostrar(arbolB));
    }//GEN-LAST:event_Mostrar8ActionPerformed

    private void vaciar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciar6ActionPerformed
        arbolB.vaciar();
    }//GEN-LAST:event_vaciar6ActionPerformed

    private void buscar6buscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar6buscar4ActionPerformed

        result.setText(String.valueOf(arbolMV.cantidadNodoHojas()));
    }//GEN-LAST:event_buscar6buscar4ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        int clave = Integer.valueOf(claveA.getText());
        result.setText( String.valueOf(arbolMV.buscar(clave) ) );
    }//GEN-LAST:event_buscarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Mostrar8;
    private javax.swing.JLabel Reconstruir1;
    private javax.swing.JLabel Reconstruir2;
    private javax.swing.JLabel Reconstruir3;
    private javax.swing.JLabel Reconstruir37;
    private javax.swing.JLabel Reconstruir38;
    private javax.swing.JLabel Reconstruir39;
    private javax.swing.JLabel Reconstruir4;
    private javax.swing.JLabel Reconstruir40;
    private javax.swing.JLabel Reconstruir5;
    private javax.swing.JLabel Reconstruir6;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar5;
    private javax.swing.JButton buscar6;
    private javax.swing.JTextField claveA;
    private javax.swing.JTextArea detalles1;
    private javax.swing.JTextArea detalles2;
    private javax.swing.JButton ejemplo1;
    private javax.swing.JButton ejmplo2;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton existe;
    private javax.swing.JButton existe5;
    private javax.swing.JButton insercion;
    private javax.swing.JButton insertar;
    private javax.swing.JButton insertar5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea mostrarArbol1;
    private javax.swing.JTextArea mostrarArbol2;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result1;
    private javax.swing.JButton similar;
    private javax.swing.JButton vaciar;
    private javax.swing.JButton vaciar6;
    private javax.swing.JTextField valorA;
    // End of variables declaration//GEN-END:variables
}
